# Generated by Django 4.0.5 on 2022-07-24 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.book'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('Error', 'Error')], default='pending', max_length=10)),
                ('authority', models.CharField(max_length=36, null=True)),
                ('refid', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.invoice')),
            ],
        ),
    ]
